//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTrace.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusStop
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Longtitude { get; set; }
        public double Lattitude { get; set; }
    }
}
